//! plan.rs — Renders OMB M-26-15 and EO 14412 post-quantum migration plans.
//! Targets the December 31, 2030 federal cryptographic transition deadline.

use crate::scan::ScanReport;

#[derive(Debug, Clone)]
pub struct MigrationPhase {
    pub phase: u32,
    pub title: String,
    pub deadline: String,
    pub description: String,
    pub affected_items: usize,
}

#[derive(Debug, Clone)]
pub struct MigrationPlan {
    pub target: String,
    pub federal_mandate: String,
    pub statutory_deadline: String,
    pub total_legacy_callsites: usize,
    pub phases: Vec<MigrationPhase>,
}

pub fn render_plan(report: &ScanReport) -> MigrationPlan {
    let total = report.findings.len();
    let phases = vec![
        MigrationPhase {
            phase: 1,
            title: "Inventory & Discovery (NIST CSWP 0218)".into(),
            deadline: "2026-12-31".into(),
            description: "Catalog all asymmetric key generation and signature call sites.".into(),
            affected_items: total,
        },
        MigrationPhase {
            phase: 2,
            title: "Hybrid Deployment (X25519 + ML-KEM-768)".into(),
            deadline: "2028-06-30".into(),
            description: "Deploy dual-key encapsulation shims across TLS and internal IPC.".into(),
            affected_items: report.rsa_count + report.ecc_count,
        },
        MigrationPhase {
            phase: 3,
            title: "Full Post-Quantum Transition (ML-DSA-65 / FIPS 204)".into(),
            deadline: "2030-12-31".into(),
            description: "Deprecate all RSA/ECDSA signing keys; enforce strict PQC verification.".into(),
            affected_items: total,
        },
    ];

    MigrationPlan {
        target: report.target.clone(),
        federal_mandate: "OMB M-26-15 / Executive Order 14412".into(),
        statutory_deadline: "2030-12-31".into(),
        total_legacy_callsites: total,
        phases,
    }
}

pub fn emit_markdown(plan: &MigrationPlan, report: &ScanReport) -> String {
    let mut out = String::new();
    out.push_str(&format!("# OMB M-26-15 Cryptographic Migration Plan\n\n"));
    out.push_str("> Generated by [Aegis](https://studio2201.com/aegis) · studio2201\n\n");
    out.push_str(&format!(
        "**Target Codebase**: `{}`  \n**Federal Mandate**: {}  \n**Statutory Deadline**: `{}`  \n**Legacy Cryptographic Sites**: {}\n\n",
        plan.target, plan.federal_mandate, plan.statutory_deadline, plan.total_legacy_callsites
    ));

    out.push_str("### Inventory by Primitive\n\n");
    out.push_str("| Primitive Class | Detected Call Sites | Post-Quantum Target |\n| :--- | :--- | :--- |\n");
    out.push_str(&format!("| RSA (FIPS 186-4) | {} | ML-KEM-768 / ML-DSA-65 |\n", report.rsa_count));
    out.push_str(&format!("| Classical ECC | {} | ML-DSA-65 (FIPS 204) |\n", report.ecc_count));
    out.push_str(&format!("| OpenSSL EVP_PKEY | {} | OQS Provider Shim |\n", report.evp_count));
    out.push_str(&format!("| Vulnerable Hash Context | {} | SHA-384 / SHAKE256 |\n\n", report.weak_hash_count));

    out.push_str("### Migration Roadmap\n\n");
    for p in &plan.phases {
        out.push_str(&format!(
            "#### Phase {}: {} (Target: `{}`)\n- **Action**: {}\n- **Affected Call Sites**: {}\n\n",
            p.phase, p.title, p.deadline, p.description, p.affected_items
        ));
    }

    if !report.findings.is_empty() {
        out.push_str("### Critical Legacy Call Sites\n\n");
        out.push_str("| File:Line | Primitive | PQC Replacement | Snippet |\n| :--- | :--- | :--- | :--- |\n");
        for f in report.findings.iter().take(15) {
            out.push_str(&format!(
                "| `{}:{}` | {} | {} | `{}` |\n",
                f.file, f.line, f.primitive, f.pqc_replacement, f.snippet
            ));
        }
    }

    out
}

pub fn emit_json(plan: &MigrationPlan, report: &ScanReport) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!("  \"target\": \"{}\",\n", plan.target));
    out.push_str(&format!("  \"federal_mandate\": \"{}\",\n", plan.federal_mandate));
    out.push_str(&format!("  \"deadline\": \"{}\",\n", plan.statutory_deadline));
    out.push_str(&format!("  \"total_legacy_callsites\": {},\n", plan.total_legacy_callsites));
    out.push_str(&format!("  \"rsa_count\": {},\n", report.rsa_count));
    out.push_str(&format!("  \"ecc_count\": {},\n", report.ecc_count));
    out.push_str(&format!("  \"evp_count\": {},\n", report.evp_count));
    out.push_str("  \"findings\": [\n");

    for (i, f) in report.findings.iter().enumerate() {
        let comma = if i + 1 < report.findings.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{\"file\": \"{}\", \"line\": {}, \"primitive\": \"{}\", \"replacement\": \"{}\"}}{}\n",
            f.file, f.line, f.primitive, f.pqc_replacement, comma
        ));
    }

    out.push_str("  ]\n");
    out.push_str("}\n");
    out
}
